package com.paypal.api.payments.enums;

public enum PaymentFailureReasonCode {
    PAYMENT_DENIED,
    INTERNAL_SERVER_ERROR,
    PAYEE_ACCOUNT_RESTRICTED,
    PAYER_ACCOUNT_RESTRICTED,
    PAYER_CANNOT_PAY,
    SENDING_LIMIT_EXCEEDED,
    TRANSACTION_RECEIVING_LIMIT_EXCEEDED,
    CURRENCY_MISMATCH
}
